---
title: "Data Clustering"
output: html_document
---

# extract single words

```{r}
require("tm")

jahre <- seq(1990, 2020, 1)



delete_words <-c("kanton", "schweiz", "zürich", "zh", "winterthur",  "deutsch", "stadt", jahre)

domains <- data %>% select(top_domain) %>% distinct()

data1 <- data %>% 
  filter(time == "Jahr") %>% 
  unnest_tokens(word, Suchanfragen, token = "words", to_lower = T, drop = F) %>% 
  filter(! word %in% delete_words) %>% 
  anti_join(get_stopwords(language = "en")) %>%
  anti_join(get_stopwords(language = "de")) %>%
  anti_join(get_stopwords(language = "fr")) %>%
  group_by(top_domain, word) %>% 
  summarise(n = n(),
              klicks = sum(Klicks),
            impressions = sum(Impressionen)) %>% 
  ungroup %>% 
  group_by(word) %>% 
  mutate(sum_impressions = sum(impressions)) %>%
  mutate(count_domains = row_number()) %>% 
  ungroup() %>% 
  filter(sum_impressions > 500 & count_domains > 1)





```

# word expressions

```{r}
data2 <- data %>% 
  filter(time == "Jahr") %>% 
  mutate(words_deleted = str_trim(removeWords(Suchanfragen, delete_words), side = "both")) %>% 
  group_by(Suchanfragen) %>%
  ungroup() %>% 
  mutate(words_clean = ifelse(nchar(words_deleted)==0, Suchanfragen, words_deleted)) %>% 
  group_by(top_domain, words_clean) %>% 
  summarise(n = n(),
              klicks = sum(Klicks),
            impressions = sum(Impressionen)) %>% 
  ungroup()

```

```{r}
library(SPARQL)

endpoint <- "https://ld.geo.admin.ch/query"

query <- "PREFIX schema: <http://schema.org/>
PREFIX gn: <http://www.geonames.org/ontology#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX dct: <http://purl.org/dc/terms/>select ?Municipality ?Name ?WKT where{
?Municipality a gn:A.ADM3 .
?Municipality schema:name ?Name .
?Municipality dct:issued ?Date .
?Municipality gn:parentADM1 ?InCanton .
?InCanton schema:name ?CantonName .
?Municipality geo:hasGeometry ?Geometry .
##?Geometry geo:asWKT ?WKT .
FILTER (?Date = \"2018-01-01\"^^xsd:date)
FILTER (?CantonName = \"Zürich\")}"


qd <- SPARQL(endpoint,query)


PREFIX schema: <http://schema.org/>
PREFIX gn: <http://www.geonames.org/ontology#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX dct: <http://purl.org/dc/terms/>
select ?Municipality ?Name ?WKT
where
{
?Municipality a gn:A.ADM3 .
?Municipality schema:name ?Name .
?Municipality dct:issued ?Date .
?Municipality gn:parentADM1 ?InCanton .
?InCanton schema:name ?CantonName .
?Municipality geo:hasGeometry ?Geometry .
##?Geometry geo:asWKT ?WKT .
FILTER (?Date = "2018-01-01"^^xsd:date)
FILTER (?CantonName = "Zürich")  
}

```


# Word stem

```{r}
data3 <- data2%>% 
  mutate(word_stem = stemDocument(words_clean, language = "german"))
```


# bigram

```{r}
data3 <- data2 %>%
  unnest_tokens(bigram, words_clean, token = "ngrams", n = 2 , drop = F) %>% 
  mutate(bigram2 = ifelse(is.na(bigram), words_clean, bigram)) %>% 
    group_by(top_domain, bigram2) %>% 
  summarise(n = sum(n),
            nn = n(),
              klicks = sum(klicks),
            impressions = sum(impressions)) %>% 
  ungroup()
```


